# Generated by Django 2.2.3 on 2019-07-19 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=30, null=True, verbose_name='宣传语')),
            ],
            options={
                'db_table': 'Slogan',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('photo', models.ImageField(null=True, upload_to='photo/%Y/%m/%d/', verbose_name='自定义图片路径')),
                ('Slogan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='Game.Slogan')),
            ],
            options={
                'verbose_name': 'Rnews',
                'verbose_name_plural': 'Rnews',
                'db_table': 'Rnews',
            },
        ),
    ]
