# Generated by Django 2.2.3 on 2019-07-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitmentnews',
            old_name='Slogan',
            new_name='slogan',
        ),
        migrations.AlterField(
            model_name='recruitmentnews',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='recruitmentnews',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='slogan',
            name='slogan',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
