# Generated by Django 2.2.3 on 2019-07-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_auto_20190720_0853'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recruitmentnews',
            table='rnew',
        ),
    ]
