# Generated by Django 2.2.3 on 2019-07-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_departmentmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentManager',
        ),
    ]
